### ISSUE TITLE
An Error Occurred! Uncaught Error: League\Flysystem\Filesystem::mimeType(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by nathanaelmartel** [thephpleague/mime-type-detection#14]
Hello, I get this error while using flysystem : 

```An Error Occurred! Uncaught Error: League\Flysystem\Filesystem::mimeType(): Return value must be of type string, null returned```

Finaly I resolve it by adding modifiyng this file : 
`vendor/league/mime-type-detection/src/FinfoMimeTypeDetector.php`

line 57 : 
`return (string) $this->extensionMap->lookupMimeType($extension);`

**Comment by frankdejonge** [comment]
This is a flysystem problem, not a problem of this library.
