### ISSUE TITLE
Looking up the extension based on a mime type

### ISSUE THREAD

**Issue by mattford** [thephpleague/mime-type-detection#22]
I have a requirement in my app to lookup the correct extension based on a mime type, for example if I had mime type `application/json` I would want `json` as the output, 

I've considered doing this using the `GeneratedExtensionToMimeTypeMap`:

```
$extension = array_search($mime, GeneratedExtensionToMimeTypeMap::MIME_TYPES_FOR_EXTENSIONS)
``` 
however the `MIME_TYPES_FOR_EXTENSIONS` is marked as Internal, so it seems this would be prone to breakage due to potential changes in the library

Is there any way of doing this in a supported way?

**Comment by paul-thebaud** [comment]
Hi, I have the same requirement as @mattford, any news on this?
It should simple to create a public API for this, may I create a PR?
Thanks.

**Comment by frankdejonge** [comment]
It was released in `1.13.0`, enjoy!

**Comment by paul-thebaud** [comment]
Hi @frankdejonge, thanks a lot! I will try this soon!

**Comment by mattford** [comment]
Only just saw this, thanks @frankdejonge, I will check it out!
