### ISSUE TITLE
In PHP8 Error Suppression operator does not silent fatal errors

### ISSUE THREAD

**Issue by Jeckerson** [thephpleague/mime-type-detection#6]
Hello!

In `FinfoMimeTypeDetector` class, there are several error suppressions, that make sense to refactor in near future, especially if package is PHP8 compliant.

https://github.com/thephpleague/mime-type-detection/blob/223be0e79678d592f4633b3155bbd2dd325b686d/src/FinfoMimeTypeDetector.php#L35

https://github.com/thephpleague/mime-type-detection/blob/223be0e79678d592f4633b3155bbd2dd325b686d/src/FinfoMimeTypeDetector.php#L54

https://github.com/thephpleague/mime-type-detection/blob/223be0e79678d592f4633b3155bbd2dd325b686d/src/FinfoMimeTypeDetector.php#L59

References:
* https://php.watch/versions/8.0/fatal-error-suppression

**Comment by frankdejonge** [comment]
Hi @Jeckerson, could you show which error you'd like to prevent. As far as I know the warning and errors are suppressed and there are no fatal errors coming from these method calls: https://3v4l.org/2OjTa

**Comment by Jeckerson** [comment]
@frankdejonge Hello, exactly, there are none errors to suppress. Because methods `file()` and `buffer()` return `string|false`. And suppressing errors is not good practice, especially for library. If there is error - end user, who is using this package, need to know about it.

**Comment by frankdejonge** [comment]
@Jeckerson unless you have concrete reasons to alter this, I will not change the implementation. Error suppression is a bad default, however, in FS land you get them even when they're not needed. This is why they are suppressed and Flysystem has done so for a very long time without problems. Feel free to state your case, of course. If your argument is "error suppression shouldn't be used" I hear you but I choose to not to act on this.
