### ISSUE TITLE
Wrong mime-type for 'js' and 'mjs'

### ISSUE THREAD

**Issue by b-strauss** [thephpleague/mime-type-detection#7]
The current mime type is `application/javascript`. As per the official html specification, servers should use `text/javascript`for JavaScript resources.

> Servers should use text/javascript for JavaScript resources. Servers should not use other JavaScript MIME types for JavaScript resources, and must not use non-JavaScript MIME types.

https://html.spec.whatwg.org/multipage/scripting.html#scriptingLanguages

**Comment by frankdejonge** [comment]
Hi,

There are official and living standards, this lib uses generated values from vendors through mime-db, which only reflects recognised sources which are displayed here: https://github.com/jshttp/mime-db

To help you fix your issue I've created a way for you to override mime-types using a decorator which is shipped in 1.8.0: https://github.com/thephpleague/mime-type-detection#provided-extension-maps
