### ISSUE TITLE
Wrong mime type for zip file in GeneratedExtensionToMimeTypeMap

### ISSUE THREAD

**Issue by Lctrs** [thephpleague/mime-type-detection#9]
In `GeneratedExtensionToMimeTypeMap` class, `zip` extension is mapped to `application/x-zip` mime type, which comes from [FlysystemProvidedMimeTypeProvider](https://github.com/thephpleague/mime-type-detection/blob/3b9dff8aaf7323590c1d2e443db701eb1f9aa0d3/src/Generation/FlysystemProvidedMimeTypeProvider.php#L71), but this is plain wrong.

`ext-finfo` returns `application/zip` for a zip file, and IANA have this one as well : https://www.iana.org/assignments/media-types/application/zip

**Comment by frankdejonge** [comment]
PR welcome 👍
